# Generated by Django 6.0 on 2026-01-06 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='python', max_length=50)),
                ('code', models.TextField()),
                ('parameters_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('function_type', models.CharField(default='script', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('total_execution_time', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.customfunction')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.customfunction')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(default='api', max_length=50)),
                ('auth_type', models.CharField(default='none', max_length=50)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
